general:
  models_folderpath: "${training.trainer.general.models_folderpath}"
  metrics_folderpath: "${training.trainer.general.metrics_folderpath}"
  model_name: "${training.trainer.model_name}"
  direction: "minimize"
  study_name: "eco-predict-hpt"
  n_trials: 1000
  n_jobs: -1
search_space:
  random_forest:
    n_estimators:
      name: "n_estimators"
      type: "int"
      low: 50
      high: 200
    max_depth:
      name: "max_depth"
      type: "int"
      low: 5
      high: 20
    min_samples_split:
      name: "min_samples_split"
      type: "float"
      low: 0.1
      high: 1.0
    min_samples_leaf:
      name: "min_samples_leaf"
      type: "float"
      low: 0.1
      high: 0.5
    max_features:
      name: "max_features"
      type: "categorical"
      choices:
        - 'sqrt'
        - 'log2'
        - null
