general:
  input_filepath: "${data_preprocessor.general.output_folderpath}/${data_preprocessor.general.suffix}"
  output_folderpath: "${hydra:runtime.cwd}/data/split"
  suffix: ["train.csv", "test.csv"]
  seed: 42
ratios:
  train_ratio: 0.8
  val_ratio: 0.0
  test_ratio: 0.2
split_tolerance: 0.01
