# defaults:
#   - override hydra/sweeper: "optuna"

hydra:
  sweeper:
    direction: "minimize"
    study_name: "eco-predict-hpt"
    storage: null
    n_trials: 10
    n_jobs: -1
    search_space:
      random_forest.n_estimators:
        type: "int"
        low: 50
        high: 200
      random_forest.max_depth:
        type: "int"
        low: 5
        high: 20
      random_forest.min_samples_split:
        type: "float"
        low: 0.1
        high: 1.0
      random_forest.min_samples_leaf:
        type: "float"
        low: 0.1
        high: 0.5
      random_forest.max_features:
        type: "categorical"
        choices:
          - 'auto'
          - 'sqrt'
          - 'log2'

general:
  data_path:
    train: "${data_processing.data_splitter.general.output_folderpath}/${data_processing.data_splitter.general.suffix[0]}"
    test: "${data_processing.data_splitter.general.output_folderpath}/${data_processing.data_splitter.general.suffix[1]}"
  models_folderpath: "${hydra:runtime.cwd}/models/weights"
  metrics_folderpath: "${hydra:runtime.cwd}/models/results"
  target_column: "2020energyuseintensity"

enable_feature_selection: true
cross_validation:
  kfold:
    n_splits: 5
    shuffle: true
    random_state: 42

model_name: "RANDOM_FOREST"
random_forest: # Follow blueprint to build other models
  n_estimators: 100
  criterion: "squared_error"
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: 1.0
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  bootstrap: true
  oob_score: false
  n_jobs: -1
  random_state: 42
  verbose: 0
  warm_start: false
  ccp_alpha: 0.0
  max_samples: null
