data_parser:
  url: "https://beta.data.gov.sg/collections/22/view"
  expected_files:
    - ListingofBuildingEnergyPerformanceData2019.xlsx
    - ListingofBuildingEnergyPerformanceData2020.csv
    - ListingofBuildingEnergyPerformanceDataforCommercialBuildings.csv
  downloads_foldername: "Downloads"
  output_folderpath: "${hydra:runtime.cwd}/data/raw"
  download_file_button_xpath: '//*[@id="__next"]/div/main/div/div[1]/div/button'
  download_button_xpath: '//*[@id="chakra-modal-:r3:"]/div[3]/button'
  dataset_xpaths:
    'ListingofBuildingEnergyPerformanceData2019.xlsx': '/html/body/div[3]/div/div[3]/div/section/div[2]/div/div[1]/div/div/div'
    'ListingofBuildingEnergyPerformanceData2020.csv': '/html/body/div[3]/div/div[3]/div/section/div[2]/div/div[2]/div/div/div'
    'ListingofBuildingEnergyPerformanceDataforCommercialBuildings.csv': '/html/body/div[3]/div/div[3]/div/section/div[2]/div/div[3]/div/div/div'

data_preprocessor:
  general:
    output_folderpath: "${hydra:runtime.cwd}/data/preprocessed"
    suffix: "preprocessed.csv"
    common_identifier: "buildingaddress"
  datasets:
    2019:
      enable_preprocessing: false
    2020:
      enable_preprocessing: true
      input_filepath: "${hydra:runtime.cwd}/data/raw/ListingofBuildingEnergyPerformanceData2020.csv"
      preprocessing_steps:
        drop_columns:
          - 'buildingname'
          - 'buildingtype'
          - 'greenmarkyearofaward'
          - 'centralisedairconditioningplantefficiency'
          - 'yearoflastchillerplantaudithealthcheck'
        remove_symbols:
          'grossfloorarea': ','
          'percentageofairconditionedfloorarea': '%'
          'averagemonthlybuildingoccupancyrate': '%'
          'percentageusageofled': '%'
        convert_dtypes:
          'grossfloorarea': float
          'percentageofairconditionedfloorarea': float
          'averagemonthlybuildingoccupancyrate': float
          'percentageusageofled': float
        impute_categorical_columns:
          'buildingsize':
            value: 'Omit'
            threshold:
          'greenmarkrating':
            value: 'Not Awarded'
          'greenmarkversion':
            value: 'Not Awarded'
        impute_numerical_columns:
          'grossfloorarea':
            strategy: 'median'
          'percentageofairconditionedfloorarea':
            strategy: 'median'
          'averagemonthlybuildingoccupancyrate':
            strategy: 'median'
          'numberofhotelrooms':
            strategy: 'constant'
            value: 0.0
          'ageofchiller':
            strategy: 'median'
          '2017':
            strategy: 'median'
          '2018':
            strategy: 'median'
          '2019':
            strategy: 'median'
          '2020':
            strategy: 'median'
        encode_columns:
          binary:
            'installationofsolarpv':
              'Y': 1
              'N': 0
          nominal:
            - 'mainbuildingfunction'
            - 'greenmarkversion'
            - 'typeofairconditioningsystem'
          ordinal:
            'buildingsize':
              'Small': 1
              'Large': 2
            'greenmarkrating':
              'Not Awarded': 1
              'Legislated': 2
              'Certified': 3
              'Gold': 4
              'GoldPlus': 5
              'Platinum': 6
        rename_columns:
          '2017': '2017energyuseintensity'
          '2018': '2018energyuseintensity'
          '2019': '2019energyuseintensity'
          '2020': '2020energyuseintensity'
    commercial:
      enable_preprocessing: false

data_splitter:
  general:
    input_filepath: "${data_preprocessor.general.output_folderpath}/${data_preprocessor.general.suffix}"
    output_folderpath: "${hydra:runtime.cwd}/data/split"
    suffix: ["train.csv", "test.csv"]
    seed: 42
  ratios:
    train_ratio: 0.8
    val_ratio: 0.0
    test_ratio: 0.2
  split_tolerance: 0.01

model:
  model_name: "RANDOM_FOREST" # "RANDOM_FOREST" or "XGBOOST"

  random_forest:
    n_estimators: 100
    criterion: "squared_error"
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 1.0
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: true
    oob_score: false
    n_jobs: -1
    random_state: 42
    verbose: 0
    warm_start: false
    ccp_alpha: 0.0
    max_samples: null

  xgboost:
    booster: gbtree
    objective: reg:squarederror
    gamma: 0
    min_child_weight: 1
    max_depth: 6
    subsample: 1
    colsample_bytree: 1
    colsample_bylevel: 1
    colsample_bynode: 1
    reg_alpha: 0
    reg_lambda: 1
    scale_pos_weight: 1
    base_score: 0.5
    tree_method: auto
    grow_policy: depthwise
    n_estimators: 100
    learning_rate: 0.3
    importance_type: gain
    n_jobs: 1
    random_state: 0
    verbosity: 1
    booster_params: {}
    validate_parameters: true


trainer:
  data_path:
    train: "${data_splitter.general.output_folderpath}/train.csv"
    test: "${data_splitter.general.output_folderpath}/test.csv"
  models_folderpath: "${hydra:runtime.cwd}/models/weights"
  metrics_folderpath: "${hydra:runtime.cwd}/models/results"
  target_column: "2020energyuseintensity"
  cross_validation:
    kfold:
      n_splits: 5
      shuffle: true
      random_state: 42

inference:
  model: "${model.model_name}"
  model_weights: "RANDOM_FOREST_20231027_183111_agitated_kilby.pkl"
  model_weights_filepath: "${trainer.models_folderpath}/${inference.model_weights}"
