defaults:
  - data_processing/data_parser/config.yaml
  - data_processing/data_preprocessor/config.yaml
  - data_processing/data_splitter/config.yaml

model:
  model_name: "RANDOM_FOREST" # "RANDOM_FOREST" or "XGBOOST"

  random_forest:
    n_estimators: 100
    criterion: "squared_error"
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: 1.0
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: true
    oob_score: false
    n_jobs: -1
    random_state: 42
    verbose: 0
    warm_start: false
    ccp_alpha: 0.0
    max_samples: null

  xgboost:
    booster: gbtree
    objective: reg:squarederror
    gamma: 0
    min_child_weight: 1
    max_depth: 6
    subsample: 1
    colsample_bytree: 1
    colsample_bylevel: 1
    colsample_bynode: 1
    reg_alpha: 0
    reg_lambda: 1
    scale_pos_weight: 1
    base_score: 0.5
    tree_method: auto
    grow_policy: depthwise
    n_estimators: 100
    learning_rate: 0.3
    importance_type: gain
    n_jobs: 1
    random_state: 0
    verbosity: 1
    booster_params: {}
    validate_parameters: true


trainer:
  data_path:
    train: "${data_splitter.general.output_folderpath}/train.csv"
    test: "${data_splitter.general.output_folderpath}/test.csv"
  models_folderpath: "${hydra:runtime.cwd}/models/weights"
  metrics_folderpath: "${hydra:runtime.cwd}/models/results"
  target_column: "2020energyuseintensity"
  feature_selection:
    enable_feature_selection: true
    permutation_importance:
      n_repeats: 30
      random_state: 42
      threshold: 6 #0.001
  cross_validation:
    kfold:
      n_splits: 5
      shuffle: true
      random_state: 42

inference:
  model: "RANDOM_FOREST"
  model_weights_filepath: "./models/weights/RANDOM_FOREST_20231027_195230_determined_edison.pkl"
  selected_features:
    - percentageusageofled
    - 2017energyuseintensity
    - typeofairconditioningsystem_District Cooling Plant
    - averagemonthlybuildingoccupancyrate
    - 2018energyuseintensity
    - 2019energyuseintensity
