name: Build Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**/*.Dockerfile'
      - '**/*.pkl'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/eco-predict-inference.Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/eco-predict:latest

    - name: Cleanup LFS objects
      run: git lfs prune
