name: Pylint and Pytest

on: [push]

jobs:
  pylint_pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Create and activate Conda environment
        run: |
          conda env create -f eco-predict-conda-env.yaml
          echo "conda activate eco-predict" >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install additional dependencies
        run: |
          conda install -c anaconda curl

      - name: Run pylint and pytest
        run: |
          conda run -n eco-predict pylint src --fail-under=6.5 --ignore=tests --disable=W1202
          conda run -n eco-predict pytest src/tests
        env:
          MOCK_DATAPATH: ${{ secrets.MOCK_DATAPATH }}

      - name: Clean up Conda environment
        run: |
          conda env remove -n eco-predict
